const express = require('express');
const routes = express.Router();
const adminRoutes = require('./admin');
const baidangRoutes = require('./baidang');
const baidang_anhRoutes = require('./baidang_anh');
const baocaoRoutes = require('./baocao');
const binhluanbaidangRoutes = require('./binhluanbaidang');
const chitietdonhangRoutes = require('./chitietdonhang');
const danhgiaRoutes = require('./danhgia');
const danhmucRoutes = require('./danhmuc');
const dichvuthueRoutes = require('./dichvuthue');
const donhangRoutes = require('./donhang');
const giaodichBaiDangRoutes = require('./giaodich_baidang');
const giohangRoutes = require('./giohang');
const likebaidangRoutes = require('./likebaidang');
const loaibaidangRoutes = require('./loaibaidang');
const mapsRoutes = require('./maps');
const nguoidungRoutes = require('./nguoidung');
const nguoidungtichdiemRoutes = require('./nguoidungtichdiem');
const sukienRoutes = require('./sukien');
const thanhtoanRoutes = require('./thanhtoan');
const thongbaoRoutes = require('./thongbao');
const tinnhanRoutes = require('./tinnhan');
const tinnhanaiRoutes = require('./tinnhanai');
const tichdiemRoutes = require('./tichdiem');
const lich_su_tich_diemRoutes = require('./lich_su_tich_diem');
const xacthuc = require('./xacthuc');
const quanHeBanBeRoutes = require('./quanHeBanBe');
const profileRoutes = require('./profile');
const zalopayRoutes = require('./zalopay'); // Add ZaloPay route

routes.use('/admin', adminRoutes);
routes.use('/baidang', baidangRoutes);
routes.use('/baidang_anh', baidang_anhRoutes);
routes.use('/baocao', baocaoRoutes);
routes.use('/binhluanbaidang', binhluanbaidangRoutes);
routes.use('/chitietdonhang', chitietdonhangRoutes);
routes.use('/danhgia', danhgiaRoutes);
routes.use('/danhmuc', danhmucRoutes);
routes.use('/dichvuthue', dichvuthueRoutes);
routes.use('/donhang', donhangRoutes);
routes.use('/giaodich_baidang', giaodichBaiDangRoutes);
routes.use('/giohang', giohangRoutes);
routes.use('/likebaidang', likebaidangRoutes);
routes.use('/loaibaidang', loaibaidangRoutes);
routes.use('/maps', mapsRoutes);
routes.use('/nguoidung', nguoidungRoutes);
routes.use('/nguoidungtichdiem', nguoidungtichdiemRoutes);
routes.use('/sukien', sukienRoutes);
routes.use('/thanhtoan', thanhtoanRoutes);
routes.use('/thongbao', thongbaoRoutes);
routes.use('/tinnhan', tinnhanRoutes);
routes.use('/tinnhanai', tinnhanaiRoutes);
routes.use('/tichdiem', tichdiemRoutes);
routes.use('/lich_su_tich_diem', lich_su_tich_diemRoutes);
routes.use('/xacthuc', xacthuc);
routes.use('/quanHeBanBe', quanHeBanBeRoutes);
routes.use('/profile', profileRoutes);
routes.use('/zalopay', zalopayRoutes); // Use ZaloPay route
module.exports = routes;
